"use strict";

function money(v){return Number(v||0).toFixed(2)}
function addDays(d,days){const x=new Date(d);x.setDate(x.getDate()+Number(days||0));return x.toISOString()}
function addMinutes(d,min){const x=new Date(d);x.setMinutes(x.getMinutes()+Number(min||0));return x.toISOString()}
function nextDue(product,from){if(product.billing_type!=="recurring")return null;if(Number(product.cycle_minutes)>0)return addMinutes(from,product.cycle_minutes);return addDays(from,product.cycle_days||30)}
function number(db){const y=new Date().getFullYear();const n=(db.sqlite.prepare("SELECT COUNT(*) c FROM invoices").get().c||0)+1;return `INV-${y}-${String(n).padStart(6,"0")}`}
function fullInvoice(db,id){const inv=db.sqlite.prepare("SELECT invoices.*, users.first_name, users.last_name, users.email, users.phone, users.whatsapp_country, users.whatsapp_number FROM invoices JOIN users ON users.id=invoices.user_id WHERE invoices.id=?").get(id);if(!inv)return null;inv.items=db.sqlite.prepare("SELECT * FROM invoice_items WHERE invoice_id=?").all(id);inv.services=db.sqlite.prepare("SELECT s.*,p.name product_name,p.description product_description FROM services s LEFT JOIN products p ON p.id=s.product_id WHERE s.invoice_id=?").all(id);inv.allocations=db.sqlite.prepare("SELECT * FROM delivery_allocations WHERE invoice_id=?").all(id);return inv}
function makeInvoice(db,userId,product,type="product",meta={}){const total=Number(product.price||0);const now=db.now();const id=db.sqlite.prepare("INSERT INTO invoices (number,user_id,type,status,subtotal,total,currency,due_at,metadata_json,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)").run(number(db),userId,type,"pending",total,total,db.normalizeCurrency(product.currency),addDays(now,3),JSON.stringify({...meta,product_id:product.id}),now).lastInsertRowid;db.sqlite.prepare("INSERT INTO invoice_items (invoice_id,item_type,reference_id,name,description,quantity,unit_price,total) VALUES (?,?,?,?,?,?,?,?)").run(id,"product",product.id,product.name,product.description||"",1,total,total);return fullInvoice(db,id)}
function takeStock(db,userId,product,invoiceId){let row=null;if(product.delivery_mode==="sequential")row=db.sqlite.prepare("SELECT * FROM product_inventory_items WHERE product_id=? AND status='available' ORDER BY order_index,id LIMIT 1").get(product.id);const text=row?row.content:(product.fixed_delivery||"");if(!text)return {ok:false,error:"No hay stock disponible."};const now=db.now();db.sqlite.prepare("INSERT INTO delivery_allocations (user_id,product_id,invoice_id,inventory_item_id,delivered_content,delivered_at) VALUES (?,?,?,?,?,?)").run(userId,product.id,invoiceId,row?row.id:null,text,now);if(row)db.sqlite.prepare("UPDATE product_inventory_items SET status='delivered', delivered_to_user_id=?, delivered_invoice_id=?, delivered_at=? WHERE id=?").run(userId,invoiceId,now,row.id);return {ok:true,text}}
function serviceFromInvoice(db,userId,product,invoiceId){db.sqlite.prepare("INSERT INTO services (user_id,product_id,invoice_id,status,next_invoice_at,created_at) VALUES (?,?,?,?,?,?)").run(userId,product.id,invoiceId,"active",nextDue(product,db.now()),db.now())}
function payWithCredits(db,invoiceId,userId){const inv=db.sqlite.prepare("SELECT * FROM invoices WHERE id=? AND user_id=?").get(invoiceId,userId);if(!inv)return {ok:false,error:"Factura no encontrada."};if(inv.status==="paid")return {ok:true,invoice:fullInvoice(db,invoiceId)};if(inv.status!=="pending")return {ok:false,error:"Factura no disponible para pago."};const wallet=db.getWallet(userId,inv.currency);if(Number(wallet.balance)<Number(inv.total))return {ok:false,error:"Crédito insuficiente."};const item=db.sqlite.prepare("SELECT * FROM invoice_items WHERE invoice_id=? AND item_type='product' LIMIT 1").get(invoiceId);const product=item?db.sqlite.prepare("SELECT * FROM products WHERE id=?").get(item.reference_id):null;if(!product)return {ok:false,error:"Producto no encontrado."};let error=null;const tx=db.sqlite.transaction(()=>{const already=fullInvoice(db,invoiceId).allocations.length>0;if(inv.type!=="renewal"&&!already){const stock=takeStock(db,userId,product,invoiceId);if(!stock.ok){error=stock.error;throw new Error(stock.error)}}db.adjustWallet({userId,currency:inv.currency,amount:-Number(inv.total),type:"invoice_payment",invoiceId,note:`Pago ${inv.number}`});db.sqlite.prepare("INSERT INTO payments (invoice_id,user_id,provider,amount,currency,status,created_at,confirmed_at) VALUES (?,?,?,?,?,?,?,?)").run(invoiceId,userId,"credits",inv.total,inv.currency,"paid",db.now(),db.now());db.sqlite.prepare("UPDATE invoices SET status='paid', payment_method='credits', paid_at=? WHERE id=?").run(db.now(),invoiceId);if(inv.type!=="renewal")serviceFromInvoice(db,userId,product,invoiceId)});try{tx()}catch(e){return {ok:false,error:error||e.message}}return {ok:true,invoice:fullInvoice(db,invoiceId)}}
function buyWithCredits(db,userId,productId){const product=db.sqlite.prepare("SELECT * FROM products WHERE id=? AND active=1").get(productId);if(!product)return {ok:false,error:"Producto no disponible."};if(product.delivery_mode==="sequential"){const c=db.sqlite.prepare("SELECT COUNT(*) c FROM product_inventory_items WHERE product_id=? AND status='available'").get(productId).c;if(c<=0)return {ok:false,error:"Sin stock disponible."}}const inv=makeInvoice(db,userId,product,"product");return payWithCredits(db,inv.id,userId)}
function cancelService(db,id,userId=null){const s=userId?db.sqlite.prepare("SELECT * FROM services WHERE id=? AND user_id=?").get(id,userId):db.sqlite.prepare("SELECT * FROM services WHERE id=?").get(id);if(!s)return {ok:false,error:"Servicio no encontrado."};db.sqlite.prepare("UPDATE services SET status='canceled', canceled_at=?, suspended_at=NULL WHERE id=?").run(db.now(),id);return {ok:true}}
function activateService(db,id){const s=db.sqlite.prepare("SELECT s.*,p.* FROM services s JOIN products p ON p.id=s.product_id WHERE s.id=?").get(id);if(!s)return {ok:false,error:"Servicio no encontrado."};db.sqlite.prepare("UPDATE services SET status='active', canceled_at=NULL, next_invoice_at=? WHERE id=?").run(nextDue(s,db.now()),id);return {ok:true}}
function deleteCanceledService(db,id){const s=db.sqlite.prepare("SELECT * FROM services WHERE id=?").get(id);if(!s)return {ok:false,error:"Servicio no encontrado."};if(s.status!=="canceled")return {ok:false,error:"Solo puedes eliminar servicios cancelados."};db.sqlite.prepare("DELETE FROM services WHERE id=?").run(id);return {ok:true}}
function setInvoiceStatus(db,id,status){const allow=["pending","paid","canceled","suspended"];if(!allow.includes(status))return {ok:false,error:"Estado inválido."};const inv=db.sqlite.prepare("SELECT * FROM invoices WHERE id=?").get(id);if(!inv)return {ok:false,error:"Factura no encontrada."};const now=db.now();const tx=db.sqlite.transaction(()=>{if(status==="paid"){db.sqlite.prepare("UPDATE invoices SET status='paid', paid_at=COALESCE(paid_at,?) WHERE id=?").run(now,id)}else if(status==="suspended"){db.sqlite.prepare("UPDATE invoices SET status='suspended', paid_at=NULL, suspended_at=? WHERE id=?").run(now,id);db.sqlite.prepare("UPDATE services SET status='suspended', suspended_at=? WHERE invoice_id=? AND status NOT IN ('canceled','suspended')").run(now,id)}else if(status==="canceled"){db.sqlite.prepare("UPDATE invoices SET status='canceled', paid_at=NULL, canceled_at=? WHERE id=?").run(now,id);db.sqlite.prepare("UPDATE services SET status='canceled', canceled_at=? WHERE invoice_id=?").run(now,id)}else{db.sqlite.prepare("UPDATE invoices SET status=?, paid_at=NULL WHERE id=?").run(status,id)}});tx();return {ok:true}}
function deleteInvoice(db,id){const inv=db.sqlite.prepare("SELECT * FROM invoices WHERE id=?").get(id);if(!inv)return {ok:false,error:"Factura no encontrada."};const active=db.sqlite.prepare("SELECT COUNT(*) c FROM services WHERE invoice_id=? AND status='active'").get(id).c;if(active>0)return {ok:false,error:"Cancela primero el servicio activo de esta factura."};const tx=db.sqlite.transaction(()=>{db.sqlite.prepare("DELETE FROM invoice_items WHERE invoice_id=?").run(id);db.sqlite.prepare("DELETE FROM payments WHERE invoice_id=?").run(id);db.sqlite.prepare("DELETE FROM delivery_allocations WHERE invoice_id=?").run(id);db.sqlite.prepare("DELETE FROM invoices WHERE id=?").run(id)});tx();return {ok:true}}
function generateRecurringInvoices(db){const now=db.now();const due=db.sqlite.prepare("SELECT s.*,p.name,p.description,p.price,p.currency,p.billing_type,p.cycle_days,p.cycle_minutes FROM services s JOIN products p ON p.id=s.product_id WHERE s.status='active' AND s.next_invoice_at IS NOT NULL AND datetime(s.next_invoice_at)<=datetime(?) LIMIT 100").all(now);let made=0;for(const s of due){const pend=db.sqlite.prepare("SELECT id FROM invoices WHERE user_id=? AND type='renewal' AND status='pending' AND metadata_json LIKE ? LIMIT 1").get(s.user_id,`%\"service_id\":${s.id}%`);const product={id:s.product_id,name:s.name,description:s.description,price:s.price,currency:s.currency,billing_type:s.billing_type,cycle_days:s.cycle_days,cycle_minutes:s.cycle_minutes};if(!pend){makeInvoice(db,s.user_id,product,"renewal",{service_id:s.id});made++}db.sqlite.prepare("UPDATE services SET next_invoice_at=? WHERE id=?").run(nextDue(product,s.next_invoice_at||now),s.id)}return made}
module.exports={money,fullInvoice,makeInvoice,payWithCredits,buyWithCredits,cancelService,activateService,deleteCanceledService,setInvoiceStatus,deleteInvoice,nextDue,generateRecurringInvoices};
